apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namepsace: default
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flask-api
          image: markandrade15/flask-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: flask-api
  namepsace: default
spec:
  type: LoadBalancer
  selector:
    app: flaskapi
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
